# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := SortingTest
ARDUINO_LIBS := AUnit AceCommon AceSorting
include ../../../EpoxyDuino/EpoxyDuino.mk
